# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'ml4u'
tagline:          ''
description:      'Machine learning'
url:              https://github.com/vkosuri/vkosuri.github.io
baseurl:          /

author:
  name:           'Mallikarjunarao Kosuri'
  url:            https://twitter.com/mallikarjunarao

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vkosuri/vkosuri.github.io
