# Site
name: 'Mallikarjunarao Kosuri'
description: ''
logo: 'assets/images/logo.png'
favicon: ''
baseurl: ''
disqus: 'mallikarjunaraokosuri'
email: 'malli.kv2@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    vkosuri:
      name:           Mallikarjunarao Kosuri
      site:           https://vkosuri.github.io/index.html
      avatar:         /assets/images/logo.jpg
      bio:            "Hi, I am Mallikarjunarao Kosuri, the author of this blog, I am developing new products from scratch and make my hands dirty with content. My job roles are evaluating Enterprise Turnkey Router and Switch products, and will work closely with the infrastructure to build a high scale testbeds. I am interested in sales, and marketing stuff as well."
      email:          malli.kv2@gmail.com
      twitter:        https://twitter.com/mallikarjunarao


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: vkosuri
      avatar: /assets/images/logo.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
