# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'vkosuri'
tagline:          'Machine Learner'
description:      'Learning <a herf="https://en.wikipedia.org/wiki/Natural_language_processing">nlp</a> and <a herf="https://en.wikipedia.org/wiki/Machine_learning">ml</a> techniques trying to apply on end products.'
url:              https://github.com/vkosuri/vkosuri.github.io
baseurl:          /

author:
  name:           'vkosuri'
  url:            https://twitter.com/mallikarjunarao

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vkosuri/vkosuri.github.io
