# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'vkosuri'
tagline:          'Machine Learner'
description:      'Learning [nlp](https://en.wikipedia.org/wiki/Natural_language_processing) and [ml](https://en.wikipedia.org/wiki/Machine_learning) techniques trying to apply on end products.''
url:              https://github.com/vkosuri/vkosuri.github.io
baseurl:          /

author:
  name:           'vkosuri'
  url:            https://twitter.com/mallikarjunarao

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vkosuri/vkosuri.github.io
